# Docker Compose con rete custom per mDNS Discovery
# Questa configurazione abilita mDNS tra container Docker
#
# Uso:
#   docker-compose -f docker-compose.mdns.yml up -d
#
# Note:
#   - Tutti i container sono sulla stessa rete bridge custom
#   - mDNS multicast funziona tra container sulla stessa rete
#   - Utile per testing locale di discovery automatico

version: '3.8'

services:
  rendezvous:
    build:
      context: ./rendezvous
    ports:
      - "8080:8080"
    networks:
      - synapse-net

  node-1:
    build: .
    ports:
      - "8001:8000"
    environment:
      - NODE_PORT=8000
      - RENDEZVOUS_URL=http://rendezvous:8080
      - OWN_URL=http://node-1:8000
      - SUBSCRIBED_CHANNELS=sviluppo_ui
      - INITIAL_BALANCE=1000
      # mDNS abilitato (default)
      - DISABLE_MDNS=false
    volumes:
      - ./data/node-1:/app/data
    depends_on:
      - rendezvous
    networks:
      - synapse-net
    # Opzionale: hostname per mDNS più leggibile
    hostname: synapse-node-1

  node-2:
    build: .
    ports:
      - "8002:8000"
    environment:
      - NODE_PORT=8000
      - RENDEZVOUS_URL=http://rendezvous:8080
      - OWN_URL=http://node-2:8000
      - SUBSCRIBED_CHANNELS=sviluppo_ui,marketing
      - INITIAL_BALANCE=1000
      - DISABLE_MDNS=false
    volumes:
      - ./data/node-2:/app/data
    depends_on:
      - rendezvous
    networks:
      - synapse-net
    hostname: synapse-node-2

  node-3:
    build: .
    ports:
      - "8003:8000"
    environment:
      - NODE_PORT=8000
      - RENDEZVOUS_URL=http://rendezvous:8080
      - OWN_URL=http://node-3:8000
      - SUBSCRIBED_CHANNELS=sviluppo_ui,marketing
      - INITIAL_BALANCE=1000
      - DISABLE_MDNS=false
    volumes:
      - ./data/node-3:/app/data
    depends_on:
      - rendezvous
    networks:
      - synapse-net
    hostname: synapse-node-3

  node-4:
    build: .
    ports:
      - "8004:8000"
    environment:
      - NODE_PORT=8000
      - RENDEZVOUS_URL=http://rendezvous:8080
      - OWN_URL=http://node-4:8000
      - SUBSCRIBED_CHANNELS=sviluppo_ui
      - INITIAL_BALANCE=1000
      - DISABLE_MDNS=false
    volumes:
      - ./data/node-4:/app/data
    depends_on:
      - rendezvous
    networks:
      - synapse-net
    hostname: synapse-node-4

# Rete bridge custom per mDNS
# Tutti i container possono fare multicast tra loro
networks:
  synapse-net:
    driver: bridge
    driver_opts:
      # Abilita multicast (necessario per mDNS)
      com.docker.network.bridge.enable_ip_masquerade: "true"
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  data-node-1:
  data-node-2:
  data-node-3:
  data-node-4:
