# NOTE: mDNS Discovery (Zeroconf) funziona automaticamente quando i nodi
# sono sulla stessa rete Docker (default bridge network).
# Per testare mDNS tra nodi Docker, tutti i nodi devono essere sulla stessa rete.
# mDNS funziona meglio in ambienti non-Docker (es. nodi su macchine diverse nella stessa LAN).
#
# Per abilitare mDNS tra container Docker, decommentare la sezione 'networks' in fondo
# e aggiungere 'networks: [synapse-net]' a ogni servizio.

services:
  rendezvous:
    build:
      context: ./rendezvous
    ports:
      - "8080:8080"

  node-1:
    build: .
    ports:
      - "8001:8000"
    environment:
      - NODE_PORT=8000
      - RENDEZVOUS_URL=http://rendezvous:8080
      - OWN_URL=http://node-1:8000
      - SUBSCRIBED_CHANNELS=sviluppo_ui
      - INITIAL_BALANCE=1000  # Saldo iniziale SP per modalità test
      - ENABLE_IMMUNE_SYSTEM=true  # Sistema immunitario proattivo
    volumes:
      - ./data/node-1:/app/data
    depends_on:
      - rendezvous

  node-2:
    build: .
    ports:
      - "8002:8000"
    environment:
      - NODE_PORT=8000
      - RENDEZVOUS_URL=http://rendezvous:8080
      - OWN_URL=http://node-2:8000
      - SUBSCRIBED_CHANNELS=sviluppo_ui,marketing
      - INITIAL_BALANCE=1000  # Saldo iniziale SP per modalità test
      - ENABLE_IMMUNE_SYSTEM=true  # Sistema immunitario proattivo
    volumes:
      - ./data/node-2:/app/data
    depends_on:
      - rendezvous

  node-3:
    build: .
    ports:
      - "8003:8000"
    environment:
      - NODE_PORT=8000
      - RENDEZVOUS_URL=http://rendezvous:8080
      - OWN_URL=http://node-3:8000
      - SUBSCRIBED_CHANNELS=sviluppo_ui,marketing
      - INITIAL_BALANCE=1000  # Saldo iniziale SP per modalità test
      - ENABLE_IMMUNE_SYSTEM=true  # Sistema immunitario proattivo
    volumes:
      - ./data/node-3:/app/data
    depends_on:
      - rendezvous

  node-4:
    build: .
    ports:
      - "8004:8000"
    environment:
      - NODE_PORT=8000
      - RENDEZVOUS_URL=http://rendezvous:8080
      - OWN_URL=http://node-4:8000
      - SUBSCRIBED_CHANNELS=sviluppo_ui
      - INITIAL_BALANCE=1000  # Saldo iniziale SP per modalità test
    volumes:
      - ./data/node-4:/app/data
    depends_on:
      - rendezvous

volumes:
  data-node-1:
  data-node-2:
  data-node-3:
  data-node-4:

# Rete personalizzata per mDNS (opzionale)
# Decommenta questa sezione e aggiungi 'networks: [synapse-net]' a ogni servizio
# per abilitare mDNS discovery tra container Docker
# networks:
#   synapse-net:
#     driver: bridge
